import type { TravelerProfile, Match, Conversation, TripBoard, Message } from './types'

export const MOCK_PROFILES: TravelerProfile[] = [
  {
    id: '1',
    name: 'Sofia',
    age: 26,
    photos: [
      'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=600&q=80',
      'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=600&q=80',
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&q=80',
    ],
    location: 'Barcelona, Spain',
    destinations: ['Bali', 'Tokyo'],
    travelDates: 'Aug – Sep 2026',
    departureDaysFromNow: 6,
    travelStyle: ['culture', 'content'],
    travelGoal: 'open',
    bio: 'Architecture student turned full-time wanderer. I travel for the food, stay for the sunsets, and always find trouble in the best markets. Ask me about my best meal in a language I didn\'t speak.',
    interests: ['Photography', 'Architecture', 'Foodie', 'Art', 'Languages'],
    budget: 'midrange',
    languages: ['Spanish', 'English', 'French'],
    height: '5\'6"',
    education: 'Universitat Politècnica de Catalunya',
    job: 'Freelance Designer',
    verified: 3,
    anthem: { title: 'Golden Hour', artist: 'JVKE' },
    reputationScore: 4.8,
    reputationCount: 12,
    distance: '2 km',
    pronouns: 'she/her',
    zodiac: '♏ Scorpio',
    familyPlans: 'Open to kids',
    pets: '🐱 Cat lover',
    drinking: '🍷 Socially',
    smoking: '🚭 Non-smoker',
    workout: '🏋️ Sometimes',
    diet: '🌿 Vegetarian',
    loveLanguage: 'Quality time',
    communicationStyle: 'Better in person',
    relationshipGoal: 'Long-term',
    prompts: [
      { question: 'The key to my heart is', answer: 'Showing up with good coffee and zero plans.' },
      { question: 'My travel superpower is', answer: 'Finding the best local restaurant with zero reviews.' },
      { question: 'Two truths and a lie', answer: 'I\'ve been to 32 countries. I hate beaches. I once cooked for 200 people.' },
    ],
  },
  {
    id: '2',
    name: 'James',
    age: 29,
    photos: [
      'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=600&q=80',
      'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=600&q=80',
    ],
    location: 'London, UK',
    destinations: ['Japan', 'New Zealand'],
    travelDates: 'Oct – Dec 2026',
    departureDaysFromNow: 23,
    travelStyle: ['adventure', 'budget'],
    travelGoal: 'friends',
    bio: 'Software engineer by day, mountain chaser by weekend. Completed the Appalachian Trail last summer and currently planning a trans-Siberian rail trip. Looking for someone equally unhinged.',
    interests: ['Hiking', 'Photography', 'Gaming', 'Fitness', 'Architecture'],
    budget: 'budget',
    languages: ['English', 'Japanese (basic)'],
    height: '6\'1"',
    education: 'University of Edinburgh',
    job: 'Senior Engineer',
    company: 'Revolut',
    verified: 4,
    anthem: { title: 'Pursuit of Happiness', artist: 'Kid Cudi' },
    reputationScore: 4.9,
    reputationCount: 8,
    distance: '5 km',
  },
  {
    id: '3',
    name: 'Priya',
    age: 24,
    photos: [
      'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=600&q=80',
      'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=600&q=80',
    ],
    location: 'Mumbai, India',
    destinations: ['Santorini', 'Lisbon', 'Cape Town'],
    travelDates: 'Jul – Aug 2026',
    departureDaysFromNow: 3,
    travelStyle: ['wellness', 'culture'],
    travelGoal: 'friends',
    bio: 'Yoga teacher & Ayurveda student. I plan trips around good sunrise spots, local farmers markets, and zero tourist traps. My packing list includes a yoga mat and a curiosity for everything.',
    interests: ['Yoga', 'Cooking', 'Wildlife', 'History', 'Volunteering'],
    budget: 'midrange',
    languages: ['Hindi', 'English', 'Marathi'],
    education: 'University of Mumbai',
    job: 'Yoga Instructor',
    verified: 2,
    anthem: { title: 'Blinding Lights', artist: 'The Weeknd' },
    reputationScore: 4.7,
    reputationCount: 5,
    distance: '3 km',
  },
  {
    id: '4',
    name: 'Lucas',
    age: 31,
    photos: [
      'https://images.unsplash.com/photo-1552058544-f2b08422138a?w=600&q=80',
      'https://images.unsplash.com/photo-1529665253569-6d01c0eaf7b6?w=600&q=80',
    ],
    location: 'São Paulo, Brazil',
    destinations: ['Morocco', 'Peru', 'Iceland'],
    travelDates: 'Jun – Sep 2026',
    departureDaysFromNow: 11,
    travelStyle: ['adventure', 'culture'],
    travelGoal: 'group',
    bio: 'Photographer. I\'ve sold photos from 47 countries and never checked a bag. Currently planning an overland route from Marrakesh to Cairo. Need one more navigator who can read a paper map.',
    interests: ['Photography', 'History', 'Architecture', 'Diving', 'Festivals'],
    budget: 'comfortable',
    languages: ['Portuguese', 'Spanish', 'English'],
    height: '5\'10"',
    education: 'ESPM São Paulo',
    job: 'Travel Photographer',
    verified: 4,
    anthem: { title: 'Fly Away', artist: 'Tones And I' },
    reputationScore: 5.0,
    reputationCount: 21,
    distance: '8 km',
  },
  {
    id: '5',
    name: 'Hana',
    age: 27,
    photos: [
      'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&q=80',
      'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=600&q=80',
    ],
    location: 'Tokyo, Japan',
    destinations: ['Paris', 'New York', 'Buenos Aires'],
    travelDates: 'Sep – Nov 2026',
    departureDaysFromNow: 47,
    travelStyle: ['luxury', 'content'],
    travelGoal: 'open',
    bio: 'Fashion consultant & content creator. I travel for the runway, the street style, and the coffee shops that look like art galleries. 200k followers, zero itinerary. Let\'s see where the city takes us.',
    interests: ['Art', 'Dancing', 'Music', 'Foodie', 'Photography'],
    budget: 'luxury',
    languages: ['Japanese', 'English', 'Korean'],
    height: '5\'4"',
    education: 'Bunka Fashion College',
    job: 'Content Creator',
    company: '@hana.world',
    verified: 3,
    anthem: { title: 'Levitating', artist: 'Dua Lipa' },
    reputationScore: 4.6,
    reputationCount: 9,
    distance: '1 km',
  },
  {
    id: '6',
    name: 'Mateo',
    age: 28,
    photos: [
      'https://images.unsplash.com/photo-1463453091185-61582044d556?w=600&q=80',
    ],
    location: 'Buenos Aires, Argentina',
    destinations: ['Southeast Asia', 'East Africa'],
    travelDates: 'Jan – Mar 2027',
    travelStyle: ['party', 'adventure'],
    travelGoal: 'group',
    bio: 'Marine biologist who surfs between dives. I\'ve tagged sharks in the Maldives and danced until sunrise in Ibiza in the same month. Looking for someone who understands that schedule.',
    interests: ['Surfing', 'Diving', 'Music', 'Wildlife', 'Nightlife'],
    budget: 'midrange',
    languages: ['Spanish', 'English'],
    height: '5\'11"',
    education: 'Universidad de Buenos Aires',
    job: 'Marine Biologist',
    verified: 2,
    distance: '12 km',
  },
]

const now = new Date()

export const MOCK_MATCHES: Match[] = [
  {
    id: 'm1',
    profile: MOCK_PROFILES[1],
    matchedAt: new Date(now.getTime() - 1000 * 60 * 30),
  },
  {
    id: 'm2',
    profile: MOCK_PROFILES[0],
    matchedAt: new Date(now.getTime() - 1000 * 60 * 60 * 2),
    lastMessage: {
      id: 'msg1',
      senderId: MOCK_PROFILES[0].id,
      text: 'Hey! I saw you\'re heading to Bali too 🌊',
      timestamp: new Date(now.getTime() - 1000 * 60 * 25),
      status: 'read',
    },
    unread: 1,
  },
  {
    id: 'm3',
    profile: MOCK_PROFILES[3],
    matchedAt: new Date(now.getTime() - 1000 * 60 * 60 * 24),
    lastMessage: {
      id: 'msg2',
      senderId: 'me',
      text: 'Morocco in June sounds incredible. What\'s your route?',
      timestamp: new Date(now.getTime() - 1000 * 60 * 60 * 3),
      status: 'delivered',
    },
    unread: 0,
  },
]

export const MOCK_CONVERSATIONS: Record<string, Message[]> = {
  'm2': [
    {
      id: 'c2_1',
      senderId: MOCK_PROFILES[0].id,
      text: 'Hey! I saw you\'re heading to Bali too 🌊',
      timestamp: new Date(now.getTime() - 1000 * 60 * 25),
      status: 'read',
    },
  ],
  'm3': [
    {
      id: 'c3_1',
      senderId: 'me',
      text: 'Morocco in June sounds incredible. What\'s your route?',
      timestamp: new Date(now.getTime() - 1000 * 60 * 60 * 3),
      status: 'delivered',
    },
    {
      id: 'c3_2',
      senderId: MOCK_PROFILES[3].id,
      text: 'Casablanca → Fes → Marrakesh → into the desert. 3 weeks. You in?',
      timestamp: new Date(now.getTime() - 1000 * 60 * 60 * 2),
      status: 'read',
    },
    {
      id: 'c3_3',
      senderId: 'me',
      text: 'That itinerary is exactly what I needed to see today',
      timestamp: new Date(now.getTime() - 1000 * 60 * 60 * 1),
      status: 'delivered',
    },
  ],
}

export const MOCK_TRIP_BOARDS: TripBoard[] = [
  {
    id: 't1',
    host: MOCK_PROFILES[3],
    destination: 'Marrakesh, Morocco',
    coverImage: 'https://images.unsplash.com/photo-1539020140153-e479b8c22e70?w=800&q=80',
    dates: 'Jun 5 – Jun 26, 2026',
    spotsTotal: 8,
    spotsFilled: 5,
    budget: 'comfortable',
    vibe: ['Culture', 'Adventure', 'Photography'],
    description: 'Overland route from Marrakesh through the Atlas Mountains to the Sahara. We\'re shooting the whole trip — photographers, videographers, creators welcome.',
  },
  {
    id: 't2',
    host: MOCK_PROFILES[2],
    destination: 'Santorini, Greece',
    coverImage: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=800&q=80',
    dates: 'Jul 14 – Jul 21, 2026',
    spotsTotal: 4,
    spotsFilled: 2,
    budget: 'midrange',
    vibe: ['Wellness', 'Sunsets', 'Chill'],
    description: 'Morning yoga, sunset dinners, and zero alarm clocks. Looking for 2 more calm, curious humans for the most beautiful island on Earth.',
  },
  {
    id: 't3',
    host: MOCK_PROFILES[1],
    destination: 'Hokkaido, Japan',
    coverImage: 'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800&q=80',
    dates: 'Oct 2 – Oct 16, 2026',
    spotsTotal: 6,
    spotsFilled: 4,
    budget: 'budget',
    vibe: ['Nature', 'Hiking', 'Local food'],
    description: 'Autumn leaves, ramen in every city, and two weeks of hiking. Budget-friendly route, hostels & local guesthouses only.',
  },
  {
    id: 't4',
    host: MOCK_PROFILES[4],
    destination: 'New York City, USA',
    coverImage: 'https://images.unsplash.com/photo-1534430480872-3498386e7856?w=800&q=80',
    dates: 'Sep 5 – Sep 12, 2026',
    spotsTotal: 3,
    spotsFilled: 1,
    budget: 'luxury',
    vibe: ['Fashion', 'Art', 'Nightlife'],
    description: 'NYFW week. I have credentials. Looking for 2 more creatives to move through the city together — shows, galleries, rooftops.',
  },
]

export const TRENDING_DESTINATIONS = [
  { name: 'Tokyo', country: 'Japan',   emoji: '🗼', image: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=400&q=80' },
  { name: 'Bali',  country: 'Indonesia',emoji: '🌺', image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=400&q=80' },
  { name: 'Paris', country: 'France',  emoji: '🗼', image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=400&q=80' },
  { name: 'Santorini', country: 'Greece', emoji: '⛵', image: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=400&q=80' },
  { name: 'Cape Town', country: 'South Africa', emoji: '🏔', image: 'https://images.unsplash.com/photo-1580060839134-75a5edca2e99?w=400&q=80' },
  { name: 'Bangkok', country: 'Thailand', emoji: '🏯', image: 'https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=400&q=80' },
]
