/**
 * PrayerKey — Batch 2 Prayer Topics
 * Targeted at high-volume Google keyword clusters identified from search data:
 * - Birthday prayers (massive cluster)
 * - Good morning / good night prayers
 * - Opening / closing prayers for meetings & church
 * - Holiday prayers (Easter, Christmas, Thanksgiving)
 * - Relationship prayers (boyfriend, girlfriend, relationship)
 * - Meal / grace prayers
 * - Bedtime prayers for kids and adults
 * - Communion & Bible study prayers
 * - Pet loss, quick recovery, quitting smoking
 * - Kids before school, bad dreams, a good day
 */

import type { PrayerTopic } from "./prayer-topics";

export const BATCH2_PRAYER_TOPICS: PrayerTopic[] = [

  // ── BIRTHDAY PRAYERS ─────────────────────────────────────────────
  { slug:"birthday-prayer-for-myself", title:"Birthday Prayer for Myself", metaDesc:"A heartfelt birthday prayer for yourself — thank God for your life, ask for His blessings and direction in this new year of your life.", category:"Celebration", keywords:["birthday prayer for myself","birthday prayer for me","prayer for my own birthday","birthday prayer to God for myself","birthday prayer for self"], samplePrayer:"Lord, today marks another year of Your faithfulness to me. I thank You for the gift of life, for every morning I woke up and You were already there. As I step into this new year of my life, I ask for Your hand to guide every step. Let this be the year of new levels, new grace, and new breakthroughs. Protect me from every plan of the enemy. Fill this chapter of my life with purpose, love, and abundance. I am here because of You. I celebrate with a grateful heart. In Jesus' name, Amen.", scripture:[{ref:"Psalm 118:24",text:"This is the day the Lord has made; let us rejoice and be glad in it."},{ref:"Jeremiah 29:11",text:"'For I know the plans I have for you,' declares the Lord, 'plans to prosper you and not to harm you.'"}], related:["birthday","gratitude","new-beginnings","blessing","purpose"] },

  { slug:"birthday-prayer-for-son", title:"Birthday Prayer for My Son", metaDesc:"A mother's or father's birthday prayer for their son. Bless your son on his special day with this powerful, love-filled prayer.", category:"Family", keywords:["birthday prayer for my son","birthday prayer for son","prayer for son's birthday","birthday prayer for a son","happy birthday prayer for my son"], samplePrayer:"Father God, today I lift my son before You with a full heart. Thank You for the gift he is to our family — his laughter, his spirit, his life. As he celebrates another birthday, I ask You to surround him with Your love and protection. Give him wisdom beyond his years. Let his path be lit by Your Word. Protect him from every harm and every wrong influence. Open doors for him that no man can shut. May he know You deeply and walk with You all his days. Happy birthday to my precious son. In Jesus' name, Amen.", scripture:[{ref:"Proverbs 22:6",text:"Train up a child in the way he should go; even when he is old he will not depart from it."},{ref:"Numbers 6:24-25",text:"The Lord bless you and keep you; the Lord make his face shine on you."}], related:["birthday","prayer-for-son","children","family","blessing"] },

  { slug:"birthday-prayer-for-daughter", title:"Birthday Prayer for My Daughter", metaDesc:"A beautiful birthday prayer for a daughter. Speak blessings, protection, and God's purpose over your daughter on her birthday.", category:"Family", keywords:["birthday prayer for my daughter","birthday prayer for daughter","prayer for daughter's birthday","happy birthday prayer for daughter","birthday prayer for a daughter"], samplePrayer:"Lord, my daughter is a treasure You placed in my hands, and today I celebrate the day You gave her to this world. Thank You for the unique way You made her — her heart, her gifts, her beautiful spirit. As she adds another year, pour Your blessings upon her life. Shield her from every harm and from voices that would diminish her worth. Let her know she is loved by You beyond measure. May she walk in confidence, in faith, and in the extraordinary purpose You have written for her. Bless every year ahead. In Jesus' name, Amen.", scripture:[{ref:"Psalm 139:14",text:"I praise you because I am fearfully and wonderfully made."},{ref:"Proverbs 31:25",text:"She is clothed with strength and dignity; she can laugh at the days to come."}], related:["birthday","prayer-for-daughter","children","family","blessing"] },

  { slug:"birthday-prayer-for-friend", title:"Birthday Prayer for a Friend", metaDesc:"A warm birthday prayer for a friend. Send your friend this prayer as a heartfelt blessing on their special day.", category:"Celebration", keywords:["birthday prayer for a friend","birthday prayer for my friend","prayer for friend's birthday","birthday prayer for best friend","happy birthday prayer for a friend"], samplePrayer:"Lord, today I lift up my dear friend on their birthday. Thank You for bringing them into my life — for the laughter we've shared, the moments that will always stay with me, and the friendship that has been a gift straight from You. On this special day, I ask You to bless them abundantly. Let this new year of their life be marked by favor, answered prayers, and deep joy. May they feel loved today — by the people around them and by You above all. Protect and guide them through every season ahead. In Jesus' name, Amen.", scripture:[{ref:"Proverbs 17:17",text:"A friend loves at all times, and a brother is born for a time of adversity."},{ref:"Numbers 6:24",text:"The Lord bless you and keep you."}], related:["birthday","friendship","blessing","gratitude","celebration"] },

  { slug:"birthday-prayer-for-sister", title:"Birthday Prayer for My Sister", metaDesc:"A loving birthday prayer for your sister. Bless your sister on her birthday with this heartfelt, God-centered prayer.", category:"Family", keywords:["birthday prayer for sister","birthday prayer for my sister","prayer for sister's birthday","happy birthday prayer for my sister","birthday blessing prayer for sister"], samplePrayer:"Lord, today I celebrate my sister — the one You gave me as a companion through life. Thank You for the bond we share, for the memories we've made, and for the love that holds us together through every season. On her birthday, I ask You to pour out extraordinary blessings on her life. Let her feel Your presence in a powerful way today. Give her health, joy, and divine direction for the road ahead. May every good thing she has hoped and prayed for begin to unfold this year. I love her dearly, and I know You love her even more. In Jesus' name, Amen.", scripture:[{ref:"Psalm 20:4",text:"May he give you the desire of your heart and make all your plans succeed."},{ref:"3 John 1:2",text:"I pray that you may enjoy good health and that all may go well with you."}], related:["birthday","family","blessing","friendship","gratitude"] },

  { slug:"birthday-prayer-for-husband", title:"Birthday Prayer for My Husband", metaDesc:"A wife's birthday prayer for her husband. Pray over your husband on his birthday with this scripture-based blessing.", category:"Marriage", keywords:["birthday prayer for my husband","birthday prayer for husband","prayer for husband's birthday","happy birthday prayer for my husband","wife's birthday prayer for husband"], samplePrayer:"Lord, today I celebrate the man You gave me — my husband, my partner, my best friend. Thank You for the life we are building together and for the man he is growing into each day. On his birthday, I speak Your blessings over him. Give him strength for every responsibility he carries. Protect his health and renew his spirit. Let this year be one of breakthrough, promotion, and extraordinary favor. May he walk in confidence knowing he is loved by You and by me. Guide his steps, guard his heart, and let Your light shine on his path. In Jesus' name, Amen.", scripture:[{ref:"Psalm 112:1-2",text:"Blessed is the man who fears the Lord... his children will be mighty in the land."},{ref:"Proverbs 3:5-6",text:"Trust in the Lord with all your heart and he will make your paths straight."}], related:["birthday","husband","marriage","blessing","love"] },

  { slug:"birthday-prayer-for-brother", title:"Birthday Prayer for My Brother", metaDesc:"A heartfelt birthday prayer for a brother. Speak God's blessings and protection over your brother on his special day.", category:"Family", keywords:["birthday prayer for my brother","birthday prayer for brother","prayer for brother's birthday","happy birthday prayer for my brother","birthday blessing for brother"], samplePrayer:"Lord, I thank You for my brother. He is a gift to our family and to me. On his birthday, I come before You asking for Your richest blessings on his life. Give him a year filled with health, joy, and divine opportunities. Let every door You've ordained for him swing wide open. Surround him with good people and godly wisdom. Protect him from every plan of the enemy. Let him grow in faith this year and know You in a deeper way. I celebrate him today with a heart full of gratitude and love. In Jesus' name, Amen.", scripture:[{ref:"Numbers 6:24-26",text:"The Lord bless you and keep you; the Lord make his face shine on you and be gracious to you."},{ref:"Psalm 91:11",text:"He will command his angels concerning you to guard you in all your ways."}], related:["birthday","family","blessing","protection","gratitude"] },

  { slug:"birthday-prayer-for-wife", title:"Birthday Prayer for My Wife", metaDesc:"A husband's birthday prayer for his wife. Honor and bless your wife on her birthday with this beautiful, heartfelt prayer.", category:"Marriage", keywords:["birthday prayer for my wife","birthday prayer for wife","prayer for wife's birthday","happy birthday prayer for my wife","husband's birthday prayer for wife"], samplePrayer:"Lord, today I celebrate the woman You blessed me with — my wife, the crown of my life. Thank You for her strength, her grace, and the love she pours into everything she does. On her birthday, I ask You to cover her with Your goodness. Let her feel cherished — by me and by You. Give her peace in the areas where she has worried. Give her joy that runs deeper than circumstances. Open new doors of opportunity and blessing in this new year of her life. May she walk in the fullness of everything You have purposed for her. I am so grateful she chose me. In Jesus' name, Amen.", scripture:[{ref:"Proverbs 31:28-29",text:"Her children arise and call her blessed; her husband also, and he praises her."},{ref:"Psalm 128:3",text:"Your wife will be like a fruitful vine within your house."}], related:["birthday","wife","marriage","blessing","love"] },

  { slug:"50th-birthday-prayer", title:"50th Birthday Prayer", metaDesc:"A special prayer for a 50th birthday — celebrating five decades of God's faithfulness and trusting Him for the next chapter.", category:"Celebration", keywords:["50th birthday prayer","prayer for 50th birthday","birthday prayer for 50 years","50th birthday prayer for a woman","50th birthday prayer for a man","50th birthday prayer for myself"], samplePrayer:"Lord, fifty years. Five decades of Your faithfulness, Your protection, and Your unending love. I stand here in awe of all You have brought me through. The mountains You moved, the valleys You carried me out of, the blessings I never deserved but received by grace. As I step into this milestone, I don't look back with regret but with gratitude. Now I ask for the next fifty to be even more glorious. Let wisdom be my companion. Let health be my portion. Let purpose drive every day. This is not a finish line — it is a launch pad. I step into my golden season with faith. In Jesus' name, Amen.", scripture:[{ref:"Psalm 71:17-18",text:"Since my youth, God, you have taught me... Even when I am old and gray, do not forsake me."},{ref:"Proverbs 16:31",text:"Gray hair is a crown of splendor; it is attained in the way of righteousness."}], related:["birthday","gratitude","new-beginnings","purpose","birthday-prayer-for-myself"] },

  { slug:"60th-birthday-prayer", title:"60th Birthday Prayer", metaDesc:"A meaningful prayer for a 60th birthday — reflecting on God's faithfulness and stepping boldly into a new decade of life.", category:"Celebration", keywords:["60th birthday prayer","prayer for 60th birthday","60th birthday prayer for a woman","60th birthday prayer for a man","60th birthday prayer for myself","60th birthday prayer for mom"], samplePrayer:"Heavenly Father, sixty years of Your grace have brought me to this moment. I have seen Your hand in the ordinary and the extraordinary. I have known Your comfort in loss and Your joy in abundance. As I celebrate this milestone, I thank You for every year, every lesson, and every person You placed in my journey. Now I ask for more — more of Your presence, more of Your purpose, more of Your peace. Let this decade be the most fruitful yet. Let my life continue to point others to You. I am not done. My story is not finished. You are still writing it. In Jesus' name, Amen.", scripture:[{ref:"Isaiah 46:4",text:"Even to your old age and gray hairs I am he, I am he who will sustain you."},{ref:"Psalm 92:14",text:"They will still bear fruit in old age, they will stay fresh and green."}], related:["birthday","gratitude","purpose","50th-birthday-prayer","birthday-prayer-for-myself"] },

  // ── GOOD MORNING & GOOD NIGHT PRAYERS ───────────────────────────
  { slug:"good-morning-prayer-for-her", title:"Good Morning Prayer for Her", metaDesc:"Send a beautiful good morning prayer for her — your girlfriend, wife, or the woman you love. Start her day with faith and love.", category:"Daily Prayer", keywords:["good morning prayer for her","good morning prayer for girlfriend","good morning prayer for a woman","morning prayer for her","good morning prayer text for her","good morning prayer for her to smile"], samplePrayer:"Lord, I lift up the woman who holds a special place in my heart. As a new day begins for her, let Your light be the first thing she feels. Give her a day filled with joy, protection, and favour. When the world gets loud, let her hear Your still small voice telling her she is loved. Guard her going out and her coming in. Let her smile today — because she is seen, she is cherished, and she is Yours. Bless every step she takes today. In Jesus' name, Amen.", scripture:[{ref:"Lamentations 3:22-23",text:"His compassions are new every morning; great is your faithfulness."},{ref:"Psalm 121:8",text:"The Lord will watch over your coming and going both now and forevermore."}], related:["morning","good-morning-prayer-for-him","love","daily","blessing"] },

  { slug:"good-morning-prayer-for-him", title:"Good Morning Prayer for Him", metaDesc:"Send a powerful good morning prayer for him — your boyfriend, husband, or the man you love. Cover him in prayer as he starts his day.", category:"Daily Prayer", keywords:["good morning prayer for him","good morning prayer for boyfriend","good morning prayer for a man","morning prayer for him","good morning prayer for my man","good morning prayer for husband"], samplePrayer:"Lord, I come to You this morning on behalf of the man I love. As he rises to face this day, go before him. Strengthen him for every task and every challenge ahead. Guard his mind and keep his heart close to Yours. Open doors of opportunity and close doors that are not meant for him. Let him feel Your hand on his life today. Give him clarity in decisions, courage in difficulty, and peace that passes understanding. Bless him in his coming in and his going out. Let this be a great day for him. In Jesus' name, Amen.", scripture:[{ref:"Psalm 5:3",text:"In the morning, Lord, you hear my voice; in the morning I lay my requests before you."},{ref:"Joshua 1:9",text:"Be strong and courageous. Do not be afraid; do not be discouraged, for the Lord your God will be with you."}], related:["morning","good-morning-prayer-for-her","love","strength","daily"] },

  { slug:"good-morning-prayer-for-wife", title:"Good Morning Prayer for My Wife", metaDesc:"A husband's good morning prayer for his wife. Start her day with this beautiful prayer of love, protection, and blessing.", category:"Marriage", keywords:["good morning prayer for my wife","good morning prayer for wife","morning prayer for wife","good morning prayer text for my wife","good morning prayer for my wife to start her day"], samplePrayer:"Lord, good morning. I come before You with gratitude for my wife — for the gift she is to me and to our family. As she begins her day, I ask You to fill it with Your presence. Guide her in every conversation and decision. Protect her on every road she travels. Give her energy for the demands of the day and peace when things feel overwhelming. Let her know she is deeply loved — by me and by You. May she step into this day with confidence, joy, and Your favour surrounding her. In Jesus' name, Amen.", scripture:[{ref:"Proverbs 31:25",text:"She is clothed with strength and dignity; she can laugh at the days to come."},{ref:"Numbers 6:24-25",text:"The Lord bless you and keep you; the Lord make his face shine on you."}], related:["morning","wife","marriage","good-morning-prayer-for-her","blessing"] },

  { slug:"good-morning-prayer-for-husband", title:"Good Morning Prayer for My Husband", metaDesc:"A wife's good morning prayer for her husband. Cover your husband in prayer as he starts his day with this blessing.", category:"Marriage", keywords:["good morning prayer for my husband","good morning prayer for husband","morning prayer for my husband","good morning prayer text for husband","prayer for husband in the morning"], samplePrayer:"Lord, as my husband wakes to a brand new day, I cover him in Your grace. Give him a warrior's strength and a shepherd's heart. Protect him in his workplace. Give him wisdom in every interaction. Let favour be his portion today — let doors open, let connections form, and let blessings overtake him. When the pressures of life push against him, remind him that You are his foundation. Let him come home at the end of this day knowing You were with him every step. I love him, Lord. Keep him safe. In Jesus' name, Amen.", scripture:[{ref:"Isaiah 40:31",text:"Those who hope in the Lord will renew their strength."},{ref:"Psalm 1:3",text:"Whatever they do prospers."}], related:["morning","husband","marriage","good-morning-prayer-for-him","blessing"] },

  { slug:"good-morning-prayer-for-friend", title:"Good Morning Prayer for a Friend", metaDesc:"Send a warm good morning prayer to a friend. Let them know you are praying for them as they start their day.", category:"Daily Prayer", keywords:["good morning prayer for a friend","good morning prayer for my friend","morning prayer for a friend","good morning prayer message for friend","good morning blessing prayer for a friend"], samplePrayer:"Lord, this morning I am thinking of my friend. I lift them up to You with a grateful heart — grateful for the friendship we share and grateful that You placed them in my life. As they start their day, let Your peace lead them. Give them favour in every situation they face. Let them sense Your presence throughout the day. When they are tired, be their strength. When they are uncertain, be their guide. Bless the work of their hands and let this be a day that marks the beginning of something beautiful in their life. In Jesus' name, Amen.", scripture:[{ref:"Psalm 143:8",text:"Let the morning bring me word of your unfailing love."},{ref:"Proverbs 17:17",text:"A friend loves at all times."}], related:["morning","friendship","blessing","good-morning-prayer-for-her","daily"] },

  { slug:"good-night-prayer-for-her", title:"Good Night Prayer for Her", metaDesc:"A sweet good night prayer for her — your girlfriend, wife, or the woman you love. Send her to sleep covered in prayer.", category:"Daily Prayer", keywords:["good night prayer for her","good night prayer for girlfriend","good night prayer for my love","good night prayer for wife","good night prayer for a woman","romantic good night prayer"], samplePrayer:"Lord, as the night settles and the world grows quiet, I lift up the woman I love to You. Let Your peace be her blanket tonight. Guard her while she sleeps — from every fear, every worry, every dark thought. Let angels watch over her. Give her rest that truly restores. Let her wake tomorrow refreshed and ready to shine. May she dream peacefully and feel in her spirit that she is protected and loved. Thank You for her. Keep her safe through the night. In Jesus' name, Amen.", scripture:[{ref:"Psalm 4:8",text:"In peace I will lie down and sleep, for you alone, Lord, make me dwell in safety."},{ref:"Psalm 91:4",text:"He will cover you with his feathers, and under his wings you will find refuge."}], related:["night","good-morning-prayer-for-her","love","sleep","peace"] },

  { slug:"good-morning-prayer-for-love", title:"Good Morning Prayer for My Love", metaDesc:"A romantic good morning prayer for the person you love. Start their day with faith, warmth, and a prayer straight from your heart.", category:"Daily Prayer", keywords:["good morning prayer for my love","good morning prayer for love","morning prayer for my love","good morning prayer for the one i love","romantic morning prayer for her","romantic morning prayer for him"], samplePrayer:"Lord, good morning. Before I do anything else today, I stop to thank You for the person I love. They are a gift I did not deserve. As their eyes open to a new day, let them feel Your warmth and mine. Surround them with Your protection. Go before them and make their path smooth. Let favour follow them all day long. Give them a heart full of joy and eyes full of hope. I pray that our love grows deeper in You and that our relationship reflects Your goodness. Bless my love today. In Jesus' name, Amen.", scripture:[{ref:"Song of Solomon 2:4",text:"He has brought me to his banquet hall, and his banner over me is love."},{ref:"1 Corinthians 13:7",text:"Love always protects, always trusts, always hopes, always perseveres."}], related:["morning","love","good-morning-prayer-for-her","good-morning-prayer-for-him","daily"] },

  // ── OPENING & CLOSING PRAYERS ────────────────────────────────────
  { slug:"opening-prayer-for-meeting", title:"Opening Prayer for a Meeting", metaDesc:"A professional opening prayer for a meeting. Invite God's guidance, wisdom, and unity into any business, church, or community meeting.", category:"Daily Prayer", keywords:["opening prayer for meeting","opening prayer for a meeting","prayer to open a meeting","short opening prayer for meeting","opening prayer for work meeting","opening prayer for board meeting"], samplePrayer:"Heavenly Father, we gather here today and we invite Your presence into this room. Before we discuss any agenda, any plan, or any decision, we acknowledge that without You, our efforts amount to nothing. Grant us wisdom beyond our own understanding. Let every word spoken be seasoned with grace and truth. Guard us from pride, from division, and from decisions we may later regret. Unite our hearts around a common purpose. We trust You to lead this meeting to the outcome You have ordained. May the result of this time together bring glory to Your name. In Jesus' name, Amen.", scripture:[{ref:"Proverbs 11:14",text:"Where there is no guidance, a people falls, but in an abundance of counselors there is safety."},{ref:"Matthew 18:20",text:"For where two or three gather in my name, there am I with them."}], related:["closing-prayer-for-meeting","opening-prayer-for-church","wisdom","guidance","work"] },

  { slug:"closing-prayer-for-meeting", title:"Closing Prayer for a Meeting", metaDesc:"A meaningful closing prayer for a meeting. End your business, church, or community meeting with gratitude and God's blessing.", category:"Daily Prayer", keywords:["closing prayer for meeting","closing prayer for a meeting","prayer to close a meeting","short closing prayer for meeting","closing prayer for work meeting","end of meeting prayer"], samplePrayer:"Lord, we come to the close of this meeting with grateful hearts. We thank You for the wisdom You provided, for the unity You preserved, and for the decisions made in this time together. Now as we go our separate ways, may the things discussed here produce real fruit. Guide the follow-through. Let every commitment be honoured and every plan be refined by Your hand. Keep us accountable to one another and to You. Go with each person as they leave this room. May our work together bring lasting good and glory to Your name. In Jesus' name, Amen.", scripture:[{ref:"Philippians 4:7",text:"The peace of God, which transcends all understanding, will guard your hearts and minds."},{ref:"Colossians 3:17",text:"Whatever you do, in word or deed, do it all in the name of the Lord Jesus."}], related:["opening-prayer-for-meeting","closing-prayer-for-bible-study","work","gratitude","wisdom"] },

  { slug:"opening-prayer-for-church", title:"Opening Prayer for Church Service", metaDesc:"A powerful opening prayer for a church service. Invite the Holy Spirit to move as your congregation gathers to worship God together.", category:"Ministry", keywords:["opening prayer for church service","opening prayer for church","prayer to open church service","opening prayer for sunday service","opening prayer for worship","church opening prayer"], samplePrayer:"Holy Spirit, we open this service to You. Not to a program, not to a performance, but to You. Fill this house with Your presence right now. Let every heart that entered distracted leave transformed. Let every burden laid down at these doors be met with Your grace. Move among us, speak through Your Word, and let no one leave the same as they came. Let the worship be genuine, the Word be powerful, and the altar be a place of real encounter. This is Your house. Have Your way today. In Jesus' name, Amen.", scripture:[{ref:"Psalm 22:3",text:"But you are holy, enthroned on the praises of Israel."},{ref:"John 4:24",text:"God is spirit, and his worshipers must worship in the Spirit and in truth."}], related:["closing-prayer-for-bible-study","church","worship","revival","ministry"] },

  { slug:"opening-prayer-for-bible-study", title:"Opening Prayer for Bible Study", metaDesc:"An anointed opening prayer for Bible study. Ask God to open your hearts and minds to understand and apply His Word.", category:"Ministry", keywords:["opening prayer for bible study","opening prayer for a bible study","prayer before bible study","prayer to open bible study","short prayer before bible study","prayer for bible study group"], samplePrayer:"Lord, we open Your Word today with expectation. Speak to us through every verse, every passage, every truth we encounter. Open our eyes to see what we have never seen before. Open our ears to hear beyond the words on the page. Let Your Holy Spirit be our Teacher, guiding us into all truth. Remove every distraction and every preconceived idea that would block what You want to say to us today. Let this Word not just inform our minds but transform our lives. Give us hearts to obey what we receive. In Jesus' name, Amen.", scripture:[{ref:"Psalm 119:18",text:"Open my eyes that I may see wonderful things in your law."},{ref:"2 Timothy 3:16",text:"All Scripture is God-breathed and is useful for teaching, rebuking, correcting and training in righteousness."}], related:["closing-prayer-for-bible-study","opening-prayer-for-church","spiritual-growth","wisdom","daily"] },

  { slug:"closing-prayer-for-bible-study", title:"Closing Prayer for Bible Study", metaDesc:"A meaningful closing prayer for Bible study. End your group session by asking God to seal His Word in your hearts and lives.", category:"Ministry", keywords:["closing prayer for bible study","closing prayer for a bible study","prayer after bible study","prayer to end bible study","short closing prayer for bible study","prayer after bible study group"], samplePrayer:"Father, thank You for opening Your Word to us today. We received truth, we received wisdom, and we received a deeper glimpse of who You are. Now as we close our time together, seal what we have heard into our hearts. Let it not return void but accomplish the purpose You intended when You inspired these words. Where You challenged us, give us the courage to change. Where You encouraged us, let that encouragement last beyond this room. May we leave here not as the same people who arrived. Let Your Word do its perfect work in each of us. In Jesus' name, Amen.", scripture:[{ref:"Isaiah 55:11",text:"So is my word that goes out from my mouth: It will not return to me empty."},{ref:"James 1:22",text:"Do not merely listen to the word, and so deceive yourselves. Do what it says."}], related:["opening-prayer-for-bible-study","spiritual-growth","church","closing-prayer-for-meeting","wisdom"] },

  { slug:"opening-prayer-for-class", title:"Opening Prayer for Class", metaDesc:"A short, powerful opening prayer for class or school assembly. Invite God's wisdom and peace into your classroom.", category:"Education", keywords:["opening prayer for class","opening prayer for school class","short opening prayer for class","prayer before class starts","opening prayer for students","opening prayer for school assembly"], samplePrayer:"Lord, as this class begins, we invite You in. Give our teacher wisdom to teach clearly and give us hearts ready to learn. Help us to be focused, respectful, and diligent. When the content is difficult, be our understanding. When attention wanders, draw us back. Let everything we learn today build us into the people You created us to be. May this classroom be a place where potential is discovered and hard work is honored. We trust You to guide this time. In Jesus' name, Amen.", scripture:[{ref:"Proverbs 4:7",text:"The beginning of wisdom is this: Get wisdom, and whatever you get, get insight."},{ref:"Colossians 3:23",text:"Whatever you do, work at it with all your heart, as working for the Lord."}], related:["school","wisdom","exam","back-to-school","college-student"] },

  // ── HOLIDAY & SEASONAL PRAYERS ───────────────────────────────────
  { slug:"easter-prayer", title:"Easter Prayer", metaDesc:"A powerful Easter prayer celebrating the resurrection of Jesus Christ. Rejoice in the empty tomb and the hope it brings to every believer.", category:"Celebration", keywords:["easter prayer","prayer for easter","easter sunday prayer","happy easter prayer","easter morning prayer","prayer for resurrection day"], samplePrayer:"Lord Jesus, You are risen! This is the word that changed everything — not just history, but my eternity. The tomb is empty. Death is defeated. Sin is forgiven. And I stand here in the light of that resurrection with a heart that cannot contain the gratitude I feel. On this Easter, I recommit my life to You — to the One who loved me enough to die and powerful enough to rise again. Let the reality of the resurrection change how I live every day. I am not the same. I am alive in You. Hallelujah! In Your name, Amen.", scripture:[{ref:"1 Corinthians 15:20",text:"But Christ has indeed been raised from the dead, the firstfruits of those who have fallen asleep."},{ref:"John 11:25",text:"I am the resurrection and the life. The one who believes in me will live, even though they die."}], related:["prayer-for-easter-sunday","prayer-for-easter-dinner","salvation","hope","worship"] },

  { slug:"prayer-for-easter-sunday", title:"Prayer for Easter Sunday", metaDesc:"A celebratory prayer for Easter Sunday. Worship the risen Christ and invite His resurrection power into your life and family.", category:"Celebration", keywords:["prayer for easter sunday","easter sunday prayer","prayer for easter sunday morning","easter sunday prayer for family","prayer for easter sunday 2026","good easter sunday prayer"], samplePrayer:"Risen Lord, on this Easter Sunday morning we come to Your empty tomb with wonder. What seemed like the end was only the beginning. What the enemy designed as defeat became the greatest victory in all of history. We gather today to declare: He is risen! We celebrate not just an event but a living Person who is still with us. Let the power of the resurrection flow through our families, our hearts, and our homes today. May every person who hears Your name today experience Your living presence. Christ is risen. He is risen indeed! In Your name, Amen.", scripture:[{ref:"Matthew 28:6",text:"He is not here; he has risen, just as he said."},{ref:"Romans 6:9",text:"We know that Christ, being raised from the dead, will never die again; death no longer has dominion over him."}], related:["easter-prayer","prayer-for-easter-dinner","thanksgiving","worship","salvation"] },

  { slug:"prayer-for-easter-dinner", title:"Prayer for Easter Dinner", metaDesc:"A warm prayer for Easter dinner — bless the food, honor the resurrection, and give thanks for family gathered at the table.", category:"Celebration", keywords:["prayer for easter dinner","easter dinner prayer","prayer before easter meal","grace for easter dinner","easter table prayer","prayer for easter family meal"], samplePrayer:"Lord of life, we gather at this table today to celebrate the most important event in history — Your resurrection. As we share this meal together, we are reminded that because of Easter, we share not just a table but an eternity. Thank You for the food before us, for the hands that prepared it, and for the family surrounding it. Bless every bite and every conversation. May the warmth around this table reflect the love You poured out on the cross and the joy of the empty tomb. We eat with grateful hearts. In Jesus' name, Amen.", scripture:[{ref:"Psalm 23:5",text:"You prepare a table before me in the presence of my enemies."},{ref:"1 Corinthians 10:31",text:"So whether you eat or drink or whatever you do, do it all for the glory of God."}], related:["easter-prayer","prayer-for-easter-sunday","prayer-before-eating","thanksgiving","family"] },

  { slug:"prayer-for-christmas", title:"Prayer for Christmas", metaDesc:"A beautiful Christmas prayer celebrating the birth of Jesus Christ. Worship Emmanuel — God with us — with this heartfelt holiday prayer.", category:"Celebration", keywords:["prayer for christmas","christmas prayer","prayer for christmas day","christmas prayer for family","prayer for christmas season","prayer for xmas"], samplePrayer:"Emmanuel — God with us. Those three words shatter every darkness, answer every longing, and change everything. On this Christmas, we pause to worship not the season, the gifts, or the gatherings — but the Person. Jesus, born in a manger, wrapped in humility, entering our broken world to make all things new. Thank You for leaving heaven for us. Thank You for the gift too great to comprehend. As we celebrate today, may every carols sung and candle lit be an act of worship to You, the Reason for this season. Let Christmas be holy in our hearts today. In Your name, Amen.", scripture:[{ref:"Luke 2:10-11",text:"Do not be afraid. I bring you good news that will cause great joy for all the people. Today in the town of David a Savior has been born to you."},{ref:"Isaiah 9:6",text:"For to us a child is born, to us a son is given."}], related:["prayer-for-christmas-dinner","thanksgiving","worship","family","blessing"] },

  { slug:"prayer-for-christmas-dinner", title:"Prayer for Christmas Dinner", metaDesc:"A heartfelt Christmas dinner prayer. Bless the food, family, and the true meaning of Christmas at your holiday table.", category:"Celebration", keywords:["prayer for christmas dinner","christmas dinner prayer","prayer before christmas meal","grace for christmas dinner","christmas table prayer","prayer for xmas dinner","prayer for xmas gathering"], samplePrayer:"Lord Jesus, we gather at this table on the day we celebrate Your arrival into our world. How fitting it is to share a meal — because You came to share life with us. Thank You for the food before us, the family around us, and for the Gift above all gifts: Yourself. Bless this Christmas meal. Let the conversation be full of warmth and the hearts around this table be full of gratitude. Bless those who could not be with us and comfort those who grieve this season. Let Your peace reign at this table and in every home today. In Your name, Amen.", scripture:[{ref:"John 1:14",text:"The Word became flesh and made his dwelling among us."},{ref:"Psalm 107:8-9",text:"Let them give thanks to the Lord for his unfailing love... for he satisfies the thirsty."}], related:["prayer-for-christmas","prayer-for-easter-dinner","prayer-before-eating","thanksgiving","family"] },

  { slug:"prayer-for-thanksgiving-dinner", title:"Prayer for Thanksgiving Dinner", metaDesc:"A sincere prayer for Thanksgiving dinner. Give thanks to God for His provision, family, and endless blessings at your Thanksgiving table.", category:"Celebration", keywords:["prayer for thanksgiving dinner","thanksgiving dinner prayer","prayer before thanksgiving meal","thanksgiving grace","prayer for thanksgiving","prayer for thanksgiving day","thanksgiving prayer for family"], samplePrayer:"Lord, we gather at this Thanksgiving table with full hearts before our plates are even full. You have been so good to us. Not just in what You have given, but in who You are — constant, faithful, and present. As we share this meal together, we thank You for the hands that prepared it, the family that surrounds it, and the provision that makes it possible. Let this not be a meal we rush through but a moment we truly treasure. Remind us that gratitude is not a once-a-year event but a daily posture. We are thankful — for everything. In Jesus' name, Amen.", scripture:[{ref:"Psalm 107:1",text:"Give thanks to the Lord, for he is good; his love endures forever."},{ref:"1 Thessalonians 5:18",text:"Give thanks in all circumstances; for this is God's will for you in Christ Jesus."}], related:["thanksgiving","prayer-before-eating","prayer-for-christmas-dinner","gratitude","family"] },

  // ── RELATIONSHIP & PERSONAL PRAYERS ─────────────────────────────
  { slug:"prayer-for-boyfriend", title:"Prayer for My Boyfriend", metaDesc:"A heartfelt prayer for your boyfriend — for his protection, growth, success, and for God to guide your relationship together.", category:"Relationships", keywords:["prayer for my boyfriend","prayer for boyfriend","prayer for my boyfriend at work","prayer for boyfriend protection","prayer for boyfriend to change","prayer for my boyfriend and i"], samplePrayer:"Lord, I lift my boyfriend to You today. He means so much to me and I know You love him even more than I do. Guide him in all his ways. Protect him wherever he goes — at work, on the road, in his mind. Give him wisdom in the decisions he faces and strength for every challenge. Soften any hard places in his heart and draw him closer to You every single day. Bless his work, his health, and his peace. And Lord, guide our relationship — let it be built on Your foundation, centered on Your love, and growing in the direction You have planned for both of us. In Jesus' name, Amen.", scripture:[{ref:"Proverbs 3:5-6",text:"Trust in the Lord with all your heart and lean not on your own understanding."},{ref:"1 Corinthians 13:4",text:"Love is patient, love is kind. It does not envy, it does not boast."}], related:["love","marriage","prayer-for-future-spouse","relationship-prayer","good-morning-prayer-for-him"] },

  { slug:"relationship-prayer", title:"Prayer for a Relationship", metaDesc:"A prayer for your relationship — for love, communication, trust, and God's guidance in building something real and lasting.", category:"Relationships", keywords:["prayer for relationship","prayer for my relationship","prayer for a relationship","prayer for love relationship","prayer for healthy relationship","prayer for our relationship"], samplePrayer:"Lord, I bring this relationship before You. You are the Author of love and every good relationship finds its root in You. I ask You to be at the center of what we are building together. Where there is pride, teach us humility. Where there is miscommunication, give us patience and clarity. Where there are wounds from the past, bring healing so they don't poison our present. Help us to choose each other daily — not just when it is easy but when it is costly. Build this relationship on the solid ground of trust, respect, and faith in You. Let it become something beautiful. In Jesus' name, Amen.", scripture:[{ref:"Ecclesiastes 4:12",text:"A cord of three strands is not quickly broken."},{ref:"Romans 12:10",text:"Be devoted to one another in love. Honor one another above yourselves."}], related:["love","marriage","prayer-for-boyfriend","prayer-for-future-spouse","marriage-restoration"] },

  // ── MEAL & GRACE PRAYERS ────────────────────────────────────────
  { slug:"prayer-before-eating", title:"Prayer Before Eating", metaDesc:"A simple, meaningful prayer before eating. Bless your food and give thanks to God for His provision before every meal.", category:"Daily Prayer", keywords:["prayer before eating","prayer before a meal","prayer to say before eating","short prayer before eating","blessing before eating","meal prayer before eating","grace before eating"], samplePrayer:"Lord, thank You for this food before us. Every bite is a reminder of Your provision and Your care. We do not take this meal for granted, knowing that there are many who go hungry today. Bless this food to nourish our bodies. Bless the hands that prepared it. And bless the time we share around this table. May even this simple act of eating remind us that You provide for us — daily, faithfully, lovingly. In Jesus' name, Amen.", scripture:[{ref:"Matthew 6:11",text:"Give us today our daily bread."},{ref:"1 Timothy 4:4",text:"For everything God created is good, and nothing is to be rejected if it is received with thanksgiving."}], related:["prayer-before-meals","prayer-for-dinner","prayer-for-thanksgiving-dinner","gratitude","daily"] },

  { slug:"prayer-for-dinner", title:"Prayer for Dinner", metaDesc:"A warm dinner prayer for your family table. Give thanks for the meal, the family, and God's daily provision with this evening prayer.", category:"Daily Prayer", keywords:["prayer for dinner","dinner prayer","prayer before dinner","evening meal prayer","family dinner prayer","grace for dinner"], samplePrayer:"Lord, as we gather around this table at the end of the day, we pause to be grateful. Grateful for the food, yes — but more grateful for the people sharing it with us. Thank You for this meal and for Your provision that made it possible. Bless every bite to strengthen and nourish us. Bless the conversations that will flow around this table. Let this dinner be more than food — let it be fellowship, warmth, and a reminder of all You have given us. We eat with thankful hearts. In Jesus' name, Amen.", scripture:[{ref:"Psalm 145:15-16",text:"The eyes of all look to you, and you give them their food at the proper time."},{ref:"Acts 2:46",text:"They broke bread in their homes and ate together with glad and sincere hearts."}], related:["prayer-before-eating","prayer-for-thanksgiving-dinner","thanksgiving","family","gratitude"] },

  // ── BEDTIME PRAYERS ──────────────────────────────────────────────
  { slug:"bedtime-prayer-for-kids", title:"Bedtime Prayer for Kids", metaDesc:"A simple, sweet bedtime prayer for children. Teach your kids to pray before sleep with this easy, comforting prayer for bedtime.", category:"Family", keywords:["bedtime prayer for kids","kids bedtime prayer","bedtime prayer for children","prayer for kids at night","prayer for kids before bed","short bedtime prayer for kids","kids prayer for sleep"], samplePrayer:"Dear Jesus, thank You for today. Thank You for keeping me safe and for all the fun things I did. I am sorry for anything I did wrong today. Please help me to do better tomorrow. Watch over me while I sleep tonight. Keep away any bad dreams and fill my night with Your peace. Thank You for Mommy and Daddy and everyone who loves me. I love You, Jesus. Good night. Amen.", scripture:[{ref:"Psalm 4:8",text:"In peace I will lie down and sleep, for you alone, Lord, make me dwell in safety."},{ref:"Psalm 121:3-4",text:"He who watches over you will not slumber."}], related:["night","sleep","prayer-for-kids-before-school","children","bedtime-prayer-for-adults"] },

  { slug:"bedtime-prayer-for-adults", title:"Bedtime Prayer for Adults", metaDesc:"A calming bedtime prayer for adults. Release the day to God, find peace, and rest in His protection as you sleep.", category:"Daily Prayer", keywords:["bedtime prayer for adults","adult bedtime prayer","bedtime prayer for grown ups","prayer before bed for adults","evening prayer before sleep","night prayer for adults","bedtime prayer for men and women"], samplePrayer:"Lord, as the night settles around me and the world grows quiet, I come to the close of this day with everything in me — the wins, the failures, the unfinished, and the unexpected. I lay it all before You. Forgive me for where I fell short today. Thank You for where Your grace carried me. I release every worry that would keep me awake — the deadlines, the relationships, the uncertainties — I place them all into Your hands. You are awake all night so I do not have to be. Watch over me. Guard this home. Give me deep, restoring sleep. I trust You. Good night, Lord. In Jesus' name, Amen.", scripture:[{ref:"Psalm 127:2",text:"He grants sleep to those he loves."},{ref:"Psalm 3:5",text:"I lie down and sleep; I wake again, because the Lord sustains me."}], related:["night","sleep","bedtime-prayer-for-kids","anxiety","rest"] },

  { slug:"prayer-for-kids-before-school", title:"Prayer for Kids Before School", metaDesc:"A short prayer for children before going to school. Ask God to protect your child, bless their learning, and give them a wonderful day.", category:"Family", keywords:["prayer for kids before school","prayer for children before school","morning prayer for kids going to school","school prayer for children","prayer to say before school","back to school prayer for kids"], samplePrayer:"Lord Jesus, I'm going to school today and I ask You to come with me. Help me to learn and understand everything my teachers share. Give me the courage to be kind to others and to stand up for what is right. When things are hard, remind me that You are with me. Help me make good friends and be a good friend. Protect me throughout the day and bring me home safely. Thank You for my school and for the chance to learn. In Jesus' name, Amen.", scripture:[{ref:"Proverbs 2:6",text:"For the Lord gives wisdom; from his mouth come knowledge and understanding."},{ref:"Psalm 91:11",text:"He will command his angels concerning you to guard you in all your ways."}], related:["back-to-school","school","children","bedtime-prayer-for-kids","morning"] },

  // ── COMMUNION & SPIRITUAL PRACTICES ─────────────────────────────
  { slug:"prayer-for-communion", title:"Prayer for Communion", metaDesc:"A reverent prayer for taking communion. Prepare your heart to receive the Lord's Supper with this prayer of reflection and faith.", category:"Ministry", keywords:["prayer for communion","communion prayer","prayer before taking communion","prayer for the lord's supper","prayer for holy communion","prayer before communion","prayer during communion"], samplePrayer:"Lord Jesus, as I prepare to receive this bread and this cup, I pause to remember what it cost You. The bread — Your body, broken for me. The cup — Your blood, poured out for the forgiveness of every sin I have ever committed. I come to this table not because I am worthy, but because You made me worthy through Your sacrifice. I examine my heart right now — I repent of every sin, release every unforgiveness, and draw near to You with faith. As I receive these elements, let them be a real encounter with You. Renew my covenant with You today. I love You, Lord. In Your name, Amen.", scripture:[{ref:"1 Corinthians 11:24-25",text:"This is my body, which is for you; do this in remembrance of me."},{ref:"1 Corinthians 11:28",text:"Everyone ought to examine themselves before they eat of the bread and drink from the cup."}], related:["church","spiritual-growth","repentance","salvation","worship"] },

  // ── PET LOSS ────────────────────────────────────────────────────
  { slug:"prayer-for-pet-loss", title:"Prayer for the Loss of a Pet", metaDesc:"A compassionate prayer for the loss of a dog, cat, or beloved pet. Find comfort in God's love when your heart is broken by grief.", category:"Grief", keywords:["prayer for dog passing","prayer for loss of pet","prayer for dog death","prayer for cat passing","prayer for pet death","prayer when pet dies","prayer for dying dog","dog passing away prayer"], samplePrayer:"Lord, I am surprised by how much this grief hurts. My pet was more than an animal — they were a companion, a source of joy, and a constant presence in my life. You created every living creature and You know the bond we shared. I bring this grief to You because You understand loss better than anyone. Comfort my heart in this tender moment. Thank You for the years of joy they brought into my life. Help me to remember the good without being consumed by the absence. Let Your peace, which passes all understanding, settle over my hurting heart today. In Jesus' name, Amen.", scripture:[{ref:"Psalm 36:6",text:"You care for people and animals alike, O Lord."},{ref:"Matthew 5:4",text:"Blessed are those who mourn, for they will be comforted."}], related:["grief","comfort","loss-of-loved-one","peace","healing"] },

  // ── HEALTH & RECOVERY ───────────────────────────────────────────
  { slug:"prayer-for-quick-recovery", title:"Prayer for Quick Recovery", metaDesc:"A prayer for quick recovery from illness, injury, or surgery. Trust God for supernatural healing and speedy restoration.", category:"Health", keywords:["prayer for quick recovery","prayer for fast recovery","prayer for speedy recovery","prayer for quick healing","short prayer for quick recovery","quick recovery prayer for a friend"], samplePrayer:"Lord, I come boldly before Your throne asking for a quick and complete recovery. You are Jehovah Rapha — the God who heals — and I am standing on that name right now. Speed up the healing process beyond what doctors expect. Let every treatment work powerfully. Let every medication do what it is supposed to do. Let this body cooperate with healing. Drive out every trace of sickness, pain, and weakness. And when the recovery comes faster than anticipated, let there be no doubt that Your hand was on it. I receive that healing now, in faith. In Jesus' name, Amen.", scripture:[{ref:"Psalm 30:2",text:"Lord my God, I called to you for help, and you healed me."},{ref:"Jeremiah 33:6",text:"I will heal them and will let them enjoy abundant peace and security."}], related:["healing","recovery","surgery","hospital","strength"] },

  { slug:"prayer-for-quitting-smoking", title:"Prayer for Quitting Smoking", metaDesc:"A prayer for strength to quit smoking. Ask God to break the hold of nicotine and give you the willpower to live free and healthy.", category:"Health", keywords:["prayer for quitting smoking","prayer to quit smoking","prayer for help quitting smoking","prayer to stop smoking","prayer for smoking addiction","prayer for nicotine addiction"], samplePrayer:"Lord, this habit has held on longer than I planned and I need Your strength to break free. My own willpower has not been enough. But You are the God who sets captives free — and I am asking You to set me free from this. Take away every craving. Fill the places where this habit lived with something better. Give me the strength to say no when the urge hits. When withdrawal is hard, be my comfort. Let my body become the healthy temple You designed it to be. I choose health. I choose freedom. I choose You. In Jesus' name, Amen.", scripture:[{ref:"1 Corinthians 6:19-20",text:"Your bodies are temples of the Holy Spirit. Honor God with your bodies."},{ref:"John 8:36",text:"If the Son sets you free, you will be free indeed."}], related:["addiction","sobriety","healing","health-discipline","strength"] },

  // ── SPECIFIC SITUATIONS ──────────────────────────────────────────
  { slug:"prayer-for-a-good-day", title:"Prayer for a Good Day", metaDesc:"A simple prayer for a good day — asking God to order your steps, protect your peace, and let everything work in your favor.", category:"Daily Prayer", keywords:["prayer for a good day","prayer for good day","prayer for today to be a good day","prayer for a great day","morning prayer for a good day","prayer for a blessed day","prayer for a wonderful day"], samplePrayer:"Lord, I want today to be a good day — but not just by luck or circumstance. I want it to be good because You are in it. Order my steps today. Go before me into every room I walk into. Put the right words in my mouth at the right time. Let my attitude reflect Your presence. When things threaten to go sideways, anchor me in Your peace. Let me see Your hand in the small details and the big moments. I declare that this is going to be a good day — because You are with me. In Jesus' name, Amen.", scripture:[{ref:"Psalm 118:24",text:"This is the day the Lord has made; let us rejoice and be glad in it."},{ref:"Proverbs 16:3",text:"Commit to the Lord whatever you do, and he will establish your plans."}], related:["morning","daily","prayer-for-today","gratitude","peace"] },

  { slug:"prayer-for-bad-dreams", title:"Prayer Against Bad Dreams and Nightmares", metaDesc:"A powerful prayer against bad dreams, nightmares, and night terrors. Take authority over your sleep and invite God's peace into your nights.", category:"Mental Health", keywords:["prayer for bad dreams","prayer against nightmares","prayer for night terrors","prayer to stop bad dreams","prayer before bed for no nightmares","prayer for peaceful sleep from bad dreams","prayer against evil dreams"], samplePrayer:"Lord, my nights have been disturbed and I come to You for restoration. You gave Your beloved sleep — and I receive that promise right now. I take authority in the name of Jesus over every nightmare, every dark image, and every disturbing vision that has invaded my sleep. I close every door that has given darkness access to my nights. As I sleep tonight, I declare that angels encamp around me. Let my dreams be peaceful or silent. Guard my mind through every hour of the night. I will wake up rested, refreshed, and at peace. In Jesus' name, Amen.", scripture:[{ref:"Psalm 91:5",text:"You will not fear the terror of night, nor the arrow that flies by day."},{ref:"Proverbs 3:24",text:"When you lie down, you will not be afraid; when you lie down, your sleep will be sweet."}], related:["sleep","night","prayer-against-nightmares","anxiety","spiritual-warfare"] },

  { slug:"prayer-for-safe-flight", title:"Prayer for a Safe Flight", metaDesc:"A calming prayer before flying. Ask God for protection, peace, and safe travel as you board your flight.", category:"Travel", keywords:["prayer for safe flight","prayer before flying","prayer for airplane travel","prayer for flight safety","prayer before boarding a plane","prayer for air travel","prayer for flying","prayer for a good flight"], samplePrayer:"Lord, I am about to fly and I place this journey entirely in Your hands. You hold the winds, You command the skies, and no aircraft is outside Your care. I ask for safe travel — from takeoff to landing. Give wisdom to the pilots and crew. Let the aircraft perform perfectly. Give me peace in my heart and calmness in my spirit. Let my arrival be smooth and on time. Cover every person on this flight with Your protection. I will not be anxious — I will trust You. In Jesus' name, Amen.", scripture:[{ref:"Psalm 91:11",text:"He will command his angels concerning you to guard you in all your ways."},{ref:"Deuteronomy 31:8",text:"The Lord himself goes before you and will be with you."}], related:["prayer-before-flying","travel","safe-journey","protection","peace"] },

  { slug:"prayer-for-new-baby", title:"Prayer for a New Baby", metaDesc:"A heartfelt prayer for a new baby — blessing the newborn, covering them in God's love, and praying for the new parents.", category:"Family", keywords:["prayer for new baby","prayer for newborn baby","prayer for a new baby","prayer for newborn","baby blessing prayer","prayer for new baby arrival","prayer for new baby and mother"], samplePrayer:"Lord, a new life has entered the world and we stand in awe. Only You could create something so precious. We welcome this baby and we dedicate them to You right now. Let Your hand be on this child from their very first breath. Protect their tiny body as it grows. Form their heart to know and love You. Give their parents wisdom, patience, and inexhaustible love. Surround this family with support and grace in these tender early days. May this child grow up to know You and to make You known. What a miracle You have given us. Thank You, Lord. In Jesus' name, Amen.", scripture:[{ref:"Psalm 127:3",text:"Children are a heritage from the Lord, offspring a reward from him."},{ref:"Psalm 139:13-14",text:"For you created my inmost being; you knit me together in my mother's womb."}], related:["newborn-baby","pregnancy","children","family","blessing"] },

  { slug:"prayer-for-blood-pressure", title:"Prayer for High Blood Pressure", metaDesc:"A faith-filled prayer for high blood pressure and cardiovascular health. Ask God to bring healing and peace to your heart and body.", category:"Health", keywords:["prayer for blood pressure","prayer for high blood pressure","prayer for hypertension","prayer to lower blood pressure","healing prayer for blood pressure","prayer for heart health and blood pressure"], samplePrayer:"Lord, You formed my heart and every vessel in my body. You know every number, every measurement, every reading. I ask You to work in my body right now — bring my blood pressure to a healthy level. Let my heart beat steadily and my vessels be clear. Guide me toward the lifestyle changes that support my health. Give my doctors wisdom in my treatment. And underneath all of this, remind me that anxiety is often at the root — so I release every worry to You. Your peace calms storms — I trust it to calm my body too. In Jesus' name, Amen.", scripture:[{ref:"Philippians 4:7",text:"The peace of God, which transcends all understanding, will guard your hearts and your minds."},{ref:"3 John 1:2",text:"I pray that you may enjoy good health and that all may go well with you."}], related:["healing","high-blood-pressure","heart-disease","stress","recovery"] },

  { slug:"prayer-for-new-job", title:"Prayer for a New Job", metaDesc:"A hopeful prayer for a new job. Trust God to open the right doors and lead you to the career opportunity He has prepared for you.", category:"Work", keywords:["prayer for new job","prayer for a new job","prayer for new employment","prayer when starting a new job","prayer before starting new job","prayer for job offer","prayer for job opportunity"], samplePrayer:"Lord, I am trusting You to open the right doors for me in this season. I need a new job — not just any job, but the right one. The one You have already prepared and the employer who needs exactly what You have placed in me. I ask You to go before me in every application, every interview, and every conversation. Give me the words to communicate my value. Open doors that no one can shut. And when the right offer comes, give me the discernment to recognize it. I refuse to settle for less than what You have planned. In Jesus' name, Amen.", scripture:[{ref:"Psalm 37:4",text:"Take delight in the Lord, and he will give you the desires of your heart."},{ref:"Isaiah 45:2",text:"I will go before you and will level the mountains; I will break down gates of bronze."}], related:["job","job-interview","job-loss","career-change","promotion"] },

  { slug:"prayer-for-our-country", title:"Prayer for Our Country", metaDesc:"A patriotic prayer for our country — for leaders, unity, justice, and God's hand over the nation in troubled times.", category:"Nation", keywords:["prayer for our country","prayer for the country","prayer for our nation","prayer for america","prayer for our land","prayer for the united states","prayer for national healing"], samplePrayer:"Lord God, this nation is Yours. You raised it up and You hold it in Your hands even now. We come to You in this hour because we see the cracks — the division, the anger, the injustice, and the confusion. But we believe that what is broken can be healed and what has gone wrong can be made right — with Your hand involved. We pray for our leaders. Give them wisdom, humility, and a commitment to what is right. We pray for unity among our people — that we would see each other as neighbors before we see each other as opponents. Heal our land, Lord. In Jesus' name, Amen.", scripture:[{ref:"2 Chronicles 7:14",text:"If my people, who are called by my name, will humble themselves and pray... I will heal their land."},{ref:"1 Timothy 2:1-2",text:"I urge, then, first of all, that petitions, prayers, intercession and thanksgiving be made for all people — for kings and all those in authority."}], related:["nation","government","prayer-for-elections","peace-in-the-world","prayer-for-leaders"] },

  { slug:"prayer-for-good-luck", title:"Prayer for Favour and Blessing", metaDesc:"A prayer for divine favour, blessing, and good fortune. Ask God to open doors, shift circumstances, and let everything work in your favour.", category:"Faith", keywords:["prayer for good luck","prayer for good fortune","prayer for favour","prayer for divine favour","prayer for luck","prayer for blessings and luck","prayer for good things to happen"], samplePrayer:"Lord, I understand that what the world calls 'luck' is actually Your sovereign favour. And today I am asking for that favour to be on my life in an undeniable way. Let good things find me. Let doors open without me having to force them. Let the right people cross my path at the right time. Let circumstances turn in my favour. I am not asking for luck — I am asking for Your hand to be obvious on my life today. Let people see Your blessing on me and wonder why. And when they ask, I will give You all the glory. In Jesus' name, Amen.", scripture:[{ref:"Psalm 5:12",text:"For you bless the righteous, O Lord; you cover him with favour as with a shield."},{ref:"Proverbs 8:35",text:"Whoever finds me finds life and receives favour from the Lord."}], related:["blessing","favor","financial-breakthrough","breakthrough","gratitude"] },
];
