import type { ReactNode } from "react";

export const metadata = {
  title: "Terms of Service — PrayerKey",
  description: "PrayerKey Terms of Service. Free to use, no account required.",
};

export default function TermsPage() {
  return (
    <article style={{ maxWidth: "760px", margin: "0 auto", padding: "0 0 100px" }}>

      {/* ── Hero ── */}
      <div className="animate-fadeUp" style={{ marginBottom: "64px" }}>
        <div style={{
          display:      "inline-flex",
          alignItems:   "center",
          padding:      "4px 12px",
          border:       "1.5px solid var(--pk-border-2)",
          borderRadius: "4px",
          marginBottom: "24px",
          background:   "var(--pk-card)",
          boxShadow:    "3px 3px 0 0 var(--pk-border)",
        }}>
          <span style={{ fontSize: "10px", fontWeight: 700, color: "var(--pk-text-3)", letterSpacing: "0.12em", textTransform: "uppercase" }}>
            Legal
          </span>
        </div>

        <h1 style={{
          fontSize:      "clamp(32px, 5vw, 56px)",
          fontWeight:    800,
          color:         "var(--pk-text)",
          margin:        "0 0 16px",
          letterSpacing: "-0.03em",
          lineHeight:    1.05,
        }}>
          Terms of Service
        </h1>
        <p style={{ fontSize: "14px", color: "var(--pk-text-3)", margin: 0, letterSpacing: "0.02em" }}>
          Last updated: April 2026
        </p>
      </div>

      {/* ── Sections ── */}
      <div style={{ display: "flex", flexDirection: "column", gap: "0" }}>

        <LegalSection title="Welcome to PrayerKey">
          By accessing or using PrayerKey at prayerkey.com, you agree to be bound by these Terms of Service. Please read them carefully before using the platform. If you do not agree with any part of these terms, you should not use PrayerKey. These terms apply to all visitors, users and anyone who accesses or uses the service.
        </LegalSection>

        <LegalSection title="What PrayerKey Is">
          PrayerKey is a free, AI-powered church companion that provides three core services: a live sermon Bible verse detection tool, an AI prayer generator, and a Bible search and cross-reference tool. PrayerKey is designed to assist pastors, church leaders and believers in their ministry and personal faith. It is provided as a free service with no subscription required.
        </LegalSection>

        <LegalSection title="Use of the Service">
          PrayerKey is intended for personal, religious, educational and church ministry use. You may use PrayerKey to generate prayers, search Bible verses, run live sermon sessions and display scriptures on a projector during church services. You may copy, share and read aloud any content generated by PrayerKey for personal or ministry purposes.

          {"\n\n"}You agree not to use PrayerKey for any unlawful purpose. You agree not to attempt to reverse-engineer, scrape, or extract data from the platform in bulk. You agree not to use PrayerKey to produce content that promotes hatred, violence or discrimination. You agree not to impersonate any person or organisation through content generated on the platform.
        </LegalSection>

        <LegalSection title="AI-Generated Content">
          PrayerKey uses artificial intelligence to generate prayers and provide Bible search results and cross-references. The content generated is produced automatically based on your input and is intended to be a helpful starting point for prayer and scripture study. AI-generated prayers are not a substitute for pastoral guidance, professional counselling or authoritative biblical scholarship.

          {"\n\n"}While PrayerKey strives for accuracy in verse detection and scripture references, we cannot guarantee that every result is perfectly accurate. Bible verse detection during live sermons relies on speech recognition technology which may occasionally produce imperfect results in challenging audio environments. You should always verify scripture references independently when preparing formal sermons or published materials.
        </LegalSection>

        <LegalSection title="Intellectual Property">
          The PrayerKey platform, including its design, code, branding and original written content, is the property of Collins Omoikhudu Asein. All rights are reserved. The prayers and scripture-based content generated for you through the platform are yours to use freely for personal and ministry purposes. Bible verses displayed on PrayerKey are drawn from publicly available translations and are used in accordance with their respective permissions.
        </LegalSection>

        <LegalSection title="No Account Required">
          PrayerKey does not require you to create an account. Because no account is created, PrayerKey does not store a personal profile for you. Sessions are not saved to a user database. Content generated during a session is not retained by PrayerKey after you leave the page.
        </LegalSection>

        <LegalSection title="Availability and Uptime">
          PrayerKey is provided on an as-is and as-available basis. We make every reasonable effort to keep the service online and functioning well, but we do not guarantee uninterrupted access. The service may be temporarily unavailable due to maintenance, updates or circumstances outside our control. We are not liable for any loss or inconvenience caused by service interruptions.
        </LegalSection>

        <LegalSection title="Third-Party Services">
          PrayerKey uses third-party AI and infrastructure services to deliver its features. These include AI language model providers for prayer generation and Bible search, and speech recognition technology for live sermon verse detection. These providers operate under their own terms of service and privacy policies. PrayerKey does not sell or transfer your data to third parties beyond what is necessary to deliver the service.
        </LegalSection>

        <LegalSection title="Disclaimer of Warranties">
          PrayerKey is provided without warranties of any kind, whether express or implied. We do not warrant that the service will be error-free, that AI-generated content will be theologically perfect, or that verse detection will achieve 100 percent accuracy in all environments. Your use of PrayerKey is at your sole discretion and risk.
        </LegalSection>

        <LegalSection title="Limitation of Liability">
          To the fullest extent permitted by law, PrayerKey and its creator shall not be liable for any indirect, incidental, special or consequential damages arising from your use of the platform. This includes but is not limited to loss of data, loss of income or any harm resulting from reliance on AI-generated content.
        </LegalSection>

        <LegalSection title="Changes to These Terms">
          We reserve the right to update these Terms of Service at any time. When we make changes, we will update the date at the top of this page. Continued use of PrayerKey after any changes constitutes your acceptance of the new terms.
        </LegalSection>

        <LegalSection title="Contact" last>
          If you have any questions about these Terms of Service, you can reach us through the PrayerKey website at prayerkey.com.
        </LegalSection>

      </div>
    </article>
  );
}

function LegalSection({ title, children, last = false }: { title: string; children: ReactNode; last?: boolean }) {
  return (
    <div style={{
      padding:      "clamp(28px, 4vw, 44px) 0",
      borderBottom: last ? "none" : "1px solid var(--pk-border)",
    }}>
      <h2 style={{
        fontSize:      "clamp(17px, 2vw, 21px)",
        fontWeight:    700,
        color:         "var(--pk-text)",
        margin:        "0 0 14px",
        letterSpacing: "-0.02em",
        lineHeight:    1.25,
      }}>
        {title}
      </h2>
      <div style={{
        fontSize:   "clamp(14px, 1.3vw, 16px)",
        color:      "var(--pk-text-2)",
        lineHeight: 1.85,
        whiteSpace: "pre-wrap",
      }}>
        {children}
      </div>
    </div>
  );
}
